os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker

addons:
  apt:
    packages:
    - sshpass

script:
- docker build -t otakushelter/reviews:1.0.${TRAVIS_BUILD_NUMBER} -f src/OtakuShelter.Reviews.Web/Dockerfile .
- docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
- docker push otakushelter/reviews:1.0.$TRAVIS_BUILD_NUMBER
- |
  sudo sshpass -p $ANSIBLE_PASSWORD ssh -o StrictHostKeyChecking=no $ANSIBLE_CONNECTION \
  "cd /root/OtakuShelter.Infrastructure/src && \
  ansible-playbook deploy.yml \
  -e \"\
  otakushelter_hosts=reviews \
  otakushelter_port=4007 \
  otakushelter_image=otakushelter/reviews \
  otakushelter_server_name=reviews.staging.otaku-shelter.ru \
  otakushelter_build_number=$TRAVIS_BUILD_NUMBER \
  otakushelter_database_password=$OTAKUSHELTER_DATABASE_PASSWORD \
  otakushelter_rabbitmq_password=$OTAKUSHELTER_RABBITMQ_PASSWORD \
  otakushelter_jwt_secret=$OTAKUSHELTER_JWT_SECRET\" \
  -i inventories/staging"